### ISSUE TITLE
Addquotes: detect automatically common commands

### ISSUE THREAD

**Issue by Theomat** [remimorvan/knowledge-clustering#45] opened 2024-08-16 08:02 UTC
There is a certain number of very common commands such as ``\ref`` and all of its variants where the user will never want to add quotes.
I believe it would be a nice quality of life improvement if these cases were not suggested by addquotes.

Steps to reproduce :

~~0) Write a PhD thesis~~
1) Write ``\ref{fig:grammar}`` with a ``grammar`` notion
2) Execute ``knowledge addquotes -t myfile.tex``  
3) For every single reference containing grammar, addquotes will offer you to add quotes.

**Comment by remimorvan** [comment] 2024-10-25 17:10
Duplicate of #22.

**Closed by remimorvan** 2024-10-25 17:10 UTC
